### ISSUE TITLE
Support for Helm charts

### ISSUE THREAD

**Issue by stevenfollis** [awslabs/specctl#9]
Existing functionality for `Kubernetes to ECS` utilizes K8S manifests, but for users with investments in Helm it would be nice to alternatively be able to scan Helm charts for conversion into ECS.

**Comment by stevenfollis** [comment]
May be more of a Readme.md update, as Helm supports outputting to YAMLs -

https://helm.sh/docs/helm/helm_template/

**Comment by CaerusKaru** [comment]
Can this be closed?
